version: '3.8'

services:
  fastappi:
    container_name: fastappi
    image: janou/fastappi
    build:
      context: ./server
      target: production
    command: >
      sh -c "uvicorn server.app.index:app --host 0.0.0.0 --reload --port 8080"
    environment:
      - SERVER_IP=${SERVER_IP}
    restart: always
    labels:
      - com.centurylinklabs.watchtower monitor-only="true"

  client:
    image: janou/reactapp
    build: ./client
    container_name: reactapp
    stdin_open: true
    tty: true
    environment:
      - WDS_SOCKET_PORT=0
    restart: always
    labels:
    - com.centurylinklabs.watchtower.monitor-only="true"

  nginx:
    restart: always
    container_name: nginx
    image: nginx
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - fastappi
      - client
    labels:
      - com.centurylinklabs.watchtower.enable=false

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3000
    environment:
      - REPO_USER=${DOCKER_USER}
      - REPO_PASS=${DOCKER_PASSWORD}
