version: '3.8'

services:
  fastappi:
    image: fastappi
    build:
      context: ./server
      target: development
    ports:
      - "8080:8080"
    volumes:
      - .:/fastapi_app
    command: >
      sh -c "uvicorn server.app.index:app  --host 0.0.0.0 --reload --port 8080"
    environment:
      - SERVER_IP=${SERVER_IP}