version: '3.8'

services:
  fastappi:
    image: janou/asseco-fastapi:1.0.0 
    build:
      context: .
      target: production
    ports:
      - "8080:8080"
    command: >
      sh -c "uvicorn app.index:app  --host 0.0.0.0 --reload --port 8080"
    environment:
      - SERVER_IP=${SERVER_IP}