version: '3.8'

services:
  fastappi:
    container_name: janou/fastappi
    image: janou/fastappi
    build:
      context: ./server
      target: production
    ports:
      - "8080:8080"
    command: >
      sh -c "uvicorn app.index:app  --host 0.0.0.0 --reload --port 8080"
    environment:
      - SERVER_IP=${SERVER_IP}

  client:
    image: janou/reactapp
    build: ./client
    container_name: reactapp
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
