version: '3.8'

services:
  fastappi:
    image: fastappi
    build:
      context: ./server
      target: development
    ports:
      - "8080:8080"
    volumes:
      - ./server:/fastapi_app/server
    command: >
      sh -c "uvicorn server.app.index:app --host 0.0.0.0 --reload --port 8080"
    environment:
      - SERVER_IP=${SERVER_IP}
    restart: always

  client:
    image: reactapp
    build: ./client
    container_name: reactapp
    ports:
      - 3000:3000
    volumes:
      - /client/node_modules
      - ./client:/client
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    restart: always

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 3050:80
    depends_on:
      - fastappi
      - client
